# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0cstomp_grpc_2\"\x07\n\x05\x45mpty\"\x1c\n\x0bTemperature\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x18\n\x07\x41verage\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x9c\x01\n\x16TempertureAlertService\x12G\n\x0bstream_temp\x12\x19.stomp_grpc_2.Temperature\x1a\x1b.stomp_grpc_2.StringMessage(\x01\x12\x39\n\x0bget_average\x12\x13.stomp_grpc_2.Empty\x1a\x15.stomp_grpc_2.Averageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_TEMPERATURE']._serialized_start=40
  _globals['_TEMPERATURE']._serialized_end=68
  _globals['_STRINGMESSAGE']._serialized_start=70
  _globals['_STRINGMESSAGE']._serialized_end=100
  _globals['_AVERAGE']._serialized_start=102
  _globals['_AVERAGE']._serialized_end=126
  _globals['_TEMPERTUREALERTSERVICE']._serialized_start=129
  _globals['_TEMPERTUREALERTSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
