# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0fpackage_manager\"\x07\n\x05\x45mpty\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x17\n\tProductId\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x8f\x01\n\x0eProductManager\x12\x42\n\x04sell\x12\x1a.package_manager.ProductId\x1a\x1e.package_manager.StringMessage\x12\x39\n\x03\x62uy\x12\x16.package_manager.Empty\x1a\x1a.package_manager.ProductIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_STRINGMESSAGE']._serialized_start=43
  _globals['_STRINGMESSAGE']._serialized_end=73
  _globals['_PRODUCTID']._serialized_start=75
  _globals['_PRODUCTID']._serialized_end=98
  _globals['_PRODUCTMANAGER']._serialized_start=101
  _globals['_PRODUCTMANAGER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
