# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x07\n\x05\x45mpty\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"9\n\x07Reading\x12\x0f\n\x07meterId\x18\x01 \x01(\x03\x12\x0c\n\x04zone\x18\x02 \x01(\t\x12\x0f\n\x07reading\x18\x03 \x01(\x03\".\n\x05Stats\x12\x18\n\x10n_total_readings\x18\x01 \x01(\x03\x12\x0b\n\x03\x61vg\x18\x02 \x01(\x02\x32N\n\x08\x41nalyzer\x12%\n\x07\x61nalyze\x12\x08.Reading\x1a\x0e.StringMessage(\x01\x12\x1b\n\tget_stats\x12\x06.Empty\x1a\x06.Statsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_STRINGMESSAGE']._serialized_start=26
  _globals['_STRINGMESSAGE']._serialized_end=56
  _globals['_READING']._serialized_start=58
  _globals['_READING']._serialized_end=115
  _globals['_STATS']._serialized_start=117
  _globals['_STATS']._serialized_end=163
  _globals['_ANALYZER']._serialized_start=165
  _globals['_ANALYZER']._serialized_end=243
# @@protoc_insertion_point(module_scope)
